// Ao3-Previewer/src/components/SplitPanel.tsx
import { useState, useCallback, useRef, type ReactNode } from 'react'
import Box from '@mui/material/Box'

interface SplitPanelProps {
  leftPanel: ReactNode
  rightPanel: ReactNode
}

const MIN_PCT = 20
const MAX_PCT = 80

export default function SplitPanel({ leftPanel, rightPanel }: SplitPanelProps) {
  const [leftWidth, setLeftWidth] = useState(50)
  const isDragging = useRef(false)
  const containerRef = useRef<HTMLDivElement>(null)

  const onMouseDown = useCallback(() => {
    isDragging.current = true

    const onMouseMove = (e: MouseEvent) => {
      if (!isDragging.current || !containerRef.current) return
      const { left, width } = containerRef.current.getBoundingClientRect()
      const pct = ((e.clientX - left) / width) * 100
      setLeftWidth(Math.min(MAX_PCT, Math.max(MIN_PCT, pct)))
    }

    const onMouseUp = () => {
      isDragging.current = false
      window.removeEventListener('mousemove', onMouseMove)
      window.removeEventListener('mouseup', onMouseUp)
    }

    window.addEventListener('mousemove', onMouseMove)
    window.addEventListener('mouseup', onMouseUp)
  }, [])

  return (
    <Box ref={containerRef} sx={{ display: 'flex', height: '100%', overflow: 'hidden' }}>
      <Box sx={{ width: `${leftWidth}%`, overflow: 'hidden' }}>{leftPanel}</Box>
      <Box
        onMouseDown={onMouseDown}
        sx={{
          width: '6px',
          flexShrink: 0,
          cursor: 'col-resize',
          backgroundColor: 'divider',
          '&:hover': { backgroundColor: 'primary.main' },
        }}
      />
      <Box sx={{ flex: 1, overflow: 'hidden' }}>{rightPanel}</Box>
    </Box>
  )
}

// Ao3Editor/src/components/SplitPanel.vue
<template>
  <div class="split-root">
    <div class="panel left" :style="{ width: leftWidth + '%' }">
      <slot name="left" />
    </div>

    <div
      class="divider"
      @mousedown="startDrag"
    />

    <div class="panel right" :style="{ width: 100 - leftWidth + '%' }">
      <slot name="right" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const leftWidth = ref(50)

let dragging = false

const startDrag = () => {
  dragging = true
  window.addEventListener('mousemove', onDrag)
  window.addEventListener('mouseup', stopDrag)
}

const onDrag = (e: MouseEvent) => {
  if (!dragging) return
  const percent = (e.clientX / window.innerWidth) * 100
  leftWidth.value = Math.min(80, Math.max(20, percent))
}

const stopDrag = () => {
  dragging = false
  window.removeEventListener('mousemove', onDrag)
  window.removeEventListener('mouseup', stopDrag)
}
</script>

<style scoped>
.split-root {
  display: flex;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.panel {
  height: 100%;
  min-width: 0;
  overflow: hidden;
}

.divider {
  width: 6px;
  cursor: col-resize;
  background-color: rgba(0, 0, 0, 0.12);
  flex-shrink: 0;
  z-index: 10;
}
</style>
