// Ao3-Previewer/src/editor/EditorInput.tsx
import { useRef, useCallback, useEffect, useState } from 'react'
import Tabs from '@mui/material/Tabs'
import Tab from '@mui/material/Tab'
import Button from '@mui/material/Button'
import IconButton from '@mui/material/IconButton'
import Divider from '@mui/material/Divider'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import DownloadIcon from '@mui/icons-material/Download'
import FormatIndentIncreaseIcon from '@mui/icons-material/FormatIndentIncrease'
import CheckCircleOutlinedIcon from '@mui/icons-material/CheckCircleOutlined'
import { toast } from 'react-toastify'
import { useCssAnalyzer } from '../composables/useCssAnalyzer'
import CssLintOverlay from '../components/CssLintOverlay'
import CssWarningBanner from '../components/CssWarningBanner'
import { formatCss } from '../utilities/formatCss'
import { useScrollState } from './scrollStateSync'
import type { PositionedWarning } from '../composables/useCssAnalyzer'

interface EditorInputProps {
  html: string
  css: string
  onHtmlChange: (html: string) => void
  onCssChange: (css: string) => void
}

type ActiveTab = 'html' | 'css'

const LINT_BUTTON_COLOR: Record<string, 'warning' | 'success' | 'error' | 'inherit'> = {
  idle: 'inherit',
  clean: 'success',
  warnings: 'warning',
  error: 'error',
}

export default function EditorInput({ html, css, onHtmlChange, onCssChange }: EditorInputProps) {
  const [tab, setTab] = useState<ActiveTab>('html')
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const { warnings, status, isAnalyzing, analyze, reset } = useCssAnalyzer()
  const { setEditorScrollRatio } = useScrollState()

  useEffect(() => {
    if (status !== 'idle') reset()
  }, [css]) // eslint-disable-line react-hooks/exhaustive-deps

  const autoFormatCss = useCallback(async () => {
    onCssChange(await formatCss(css))
  }, [css, onCssChange])

  const validateCss = useCallback(() => {
    analyze(css)
  }, [css, analyze])

  const onJumpToWarning = useCallback((w: PositionedWarning) => {
    const textarea = textareaRef.current
    if (!textarea || !w.line) return
    const lineHeight = 20
    textarea.scrollTop = (w.line - 1) * lineHeight
    textarea.focus()
  }, [])

  const copyToClipboard = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(tab === 'html' ? html : css)
      toast.success(`Copied ${tab.toUpperCase()} to clipboard!`, { position: 'top-center' })
    } catch {
      toast.error('Failed to copy.', { position: 'top-center' })
    }
  }, [tab, html, css])

  const saveToFile = useCallback(() => {
    const content = tab === 'html' ? html : css
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = tab === 'html' ? 'html.txt' : 'css.txt'
    a.click()
    URL.revokeObjectURL(url)
  }, [tab, html, css])

  const onScroll = useCallback(() => {
    if (tab !== 'html') return
    const el = textareaRef.current
    if (!el) return
    const max = el.scrollHeight - el.clientHeight
    if (max > 0) setEditorScrollRatio(el.scrollTop / max)
  }, [tab, setEditorScrollRatio])

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <Tabs value={tab} onChange={(_, v) => setTab(v)}>
        <Tab label="HTML" value="html" />
        <Tab label="CSS" value="css" />
      </Tabs>
      <Divider />

      {/* Editor body */}
      <div style={{ position: 'relative', flex: 1, padding: '8px', minHeight: 0 }}>
        {/* Outlined textarea container */}
        <div
          style={{
            position: 'relative',
            height: '100%',
            border: '1px solid rgba(0,0,0,0.23)',
            borderRadius: '4px',
            overflow: 'hidden',
          }}
        >
          <textarea
            ref={textareaRef}
            value={tab === 'html' ? html : css}
            onChange={(e) =>
              tab === 'html' ? onHtmlChange(e.target.value) : onCssChange(e.target.value)
            }
            onScroll={onScroll}
            placeholder={tab === 'html' ? 'Write HTML here' : 'Write CSS here'}
            spellCheck={false}
            style={{
              width: '100%',
              height: '100%',
              resize: 'none',
              border: 'none',
              outline: 'none',
              fontFamily: "'Lucida Grande', 'Verdana'",
              fontSize: '14px',
              lineHeight: '20px',
              padding: '8px',
              boxSizing: 'border-box',
            }}
          />
          {tab === 'css' && (
            <CssLintOverlay warnings={warnings} rawCss={css} textareaRef={textareaRef} />
          )}
        </div>

        {/* Floating copy button */}
        <div style={{ position: 'absolute', top: '16px', right: '16px' }}>
          <IconButton size="small" onClick={copyToClipboard}>
            <ContentCopyIcon fontSize="small" />
          </IconButton>
        </div>
      </div>

      {/* Warning banner sits between body and footer */}
      {tab === 'css' && status !== 'idle' && (
        <CssWarningBanner
          warnings={warnings}
          visible={status !== 'idle'}
          onDismiss={reset}
          onJump={onJumpToWarning}
        />
      )}

      {/* Footer */}
      <div
        style={{
          flexShrink: 0,
          height: '36px',
          display: 'flex',
          justifyContent: 'space-between',
          padding: '4px 8px',
        }}
      >
        <Button size="small" variant="text" startIcon={<DownloadIcon />} onClick={saveToFile}>
          Export
        </Button>
        {tab === 'css' && (
          <>
            <Button
              size="small"
              variant="text"
              startIcon={<CheckCircleOutlinedIcon />}
              color={LINT_BUTTON_COLOR[status]}
              disabled={isAnalyzing}
              onClick={validateCss}
            >
              Validate CSS
            </Button>
            <Button
              size="small"
              variant="text"
              startIcon={<FormatIndentIncreaseIcon />}
              onClick={autoFormatCss}
            >
              Format CSS
            </Button>
          </>
        )}
      </div>
    </div>
  )
}

// Ao3Editor/src/editor/EditorInput.vue
<template>
  <div class="editor-root">
    <v-tabs v-model="tab" color="primary">
      <v-tab value="html">HTML</v-tab>
      <v-tab value="css">CSS</v-tab>
    </v-tabs>
    <v-divider />

    <div class="editor-body">
      <v-textarea
        v-if="tab === 'html'"
        v-model="localHtml"
        ref="textareaWrapper"
        placeholder="Write HTML here"
        variant="outlined"
        hide-details
        class="editor-textarea"
        rows="1"
        no-resize
        @scroll.passive="onScroll"
      />

      <v-textarea
        v-else
        v-model="localCss"
        ref="textareaWrapper"
        placeholder="Write CSS here"
        variant="outlined"
        hide-details
        class="editor-textarea"
        rows="1"
        no-resize
        @scroll.passive="onScroll"
      />
      <div class="copy-button">
        <v-btn icon rounded size="small" @click="copyToClipboard"
          ><v-icon>mdi-content-copy</v-icon></v-btn
        >
      </div>
    </div>
    <!-- Button row -->
    <div class="editor-footer">
      <v-btn size="small" variant="text" prepend-icon="mdi-download" @click="saveToFile">
        Export
      </v-btn>
      <v-btn
        v-if="tab === 'css'"
        size="small"
        variant="text"
        prepend-icon="mdi-format-indent-increase"
        @click="autoFormatCss"
      >
        Format CSS
      </v-btn>

      <!-- <v-btn
        v-else
        size="small"
        variant="text"
        prepend-icon="mdi-format-indent-increase"
        @click="autoFormatHtml"
      >
        Format HTML
      </v-btn> -->
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, nextTick, type ComponentPublicInstance } from 'vue'
import { toast, type ToastOptions } from 'vue3-toastify'
import { editorScrollRatio, isSyncingScroll } from './scrollStateSync.ts'
import { formatCss } from '@/editor/formatCss'
// import { formatHtml, formatHtmlAo3 } from '@/editor/formatHTML'

const props = defineProps<{
  html?: string
  css?: string
}>()

const emit = defineEmits<{
  (e: 'update:html', v: string): void
  (e: 'update:css', v: string): void
}>()

const tab = ref<'html' | 'css'>('html')
const localHtml = ref(props.html ?? '')
const localCss = ref(props.css ?? '')

// scroll variables
const textareaWrapper = ref<ComponentPublicInstance | null>(null)
let textareaEl: HTMLTextAreaElement | null = null

watch(localHtml, (v) => emit('update:html', v))
watch(localCss, (v) => emit('update:css', v))

async function autoFormatCss() {
  localCss.value = await formatCss(localCss.value)
}

async function copyToClipboard() {
  try {
    if (tab.value === 'html') {
      await navigator.clipboard.writeText(localHtml.value)
      toast.success('Copied HTML to clipboard!', {
        autoClose: 3000,
        position: toast.POSITION.TOP_CENTER,
      } as ToastOptions)
    } else if (tab.value === 'css') {
      await navigator.clipboard.writeText(localCss.value)
      toast.success('Copied CSS to clipboard!', {
        autoClose: 3000,
        position: toast.POSITION.TOP_CENTER,
      } as ToastOptions)
    }
  } catch ($e) {
    toast.error('Failed to copy.', {
      autoClose: 3000,
      position: toast.POSITION.TOP_CENTER,
    } as ToastOptions)
    console.log($e)
  }
}

// Source - https://stackoverflow.com/a/19332584
// Posted by NatureShade, modified by community. See post 'Timeline' for change history
// Retrieved 2026-02-12, License - CC BY-SA 4.0

function saveToFile() {
  if (tab.value === 'html') {
    const textFileAsBlob = new Blob([localHtml.value], { type: 'text/plain' })
    const downloadLink = document.createElement('a')
    downloadLink.download = "html.txt"
    downloadLink.innerHTML = 'Download File'
    if (window.webkitURL != null) {
      // Chrome allows the link to be clicked
      // without actually adding it to the DOM.
      downloadLink.href = window.webkitURL.createObjectURL(textFileAsBlob)
    } else {
      // Firefox requires the link to be added to the DOM
      // before it can be clicked.
      downloadLink.href = window.URL.createObjectURL(textFileAsBlob)
      // downloadLink.onclick = destroyClickedElement;
      downloadLink.style.display = 'none'
      document.body.appendChild(downloadLink)
    }
    downloadLink.click()
  } else if (tab.value === 'css') {
    const textFileAsBlob = new Blob([localCss.value], { type: 'text/plain' })
    const downloadLink = document.createElement('a')
    downloadLink.download = "css.txt"
    downloadLink.innerHTML = 'Download File'
    if (window.webkitURL != null) {
      // Chrome allows the link to be clicked
      // without actually adding it to the DOM.
      downloadLink.href = window.webkitURL.createObjectURL(textFileAsBlob)
    } else {
      // Firefox requires the link to be added to the DOM
      // before it can be clicked.
      downloadLink.href = window.URL.createObjectURL(textFileAsBlob)
      // downloadLink.onclick = destroyClickedElement;
      downloadLink.style.display = 'none'
      document.body.appendChild(downloadLink)
    }
    downloadLink.click()
  }
}

const onScroll = () => {
  if (isSyncingScroll.value || !textareaEl) return

  const maxScroll = textareaEl.scrollHeight - textareaEl.clientHeight
  if (maxScroll <= 0) return

  editorScrollRatio.value = textareaEl.scrollTop / maxScroll
}

onMounted(async () => {
  await nextTick()

  textareaEl = textareaWrapper.value?.$el?.querySelector('textarea') ?? null
})
</script>

<style scoped>
.editor-root {
  display: flex;
  flex-direction: column;
  height: 100%; /* ← NOT 100vh */
  width: 100%;
}

.editor-body {
  position: relative;
  flex: 1;
  padding: 8px;
  min-height: 0; /* ← critical for textarea + flex */
}

.copy-button {
  position: absolute;
  top: 16px;
  right: 16px;
}

.editor-textarea {
  height: 100%;
  font-family: 'Lucida Grande', 'Verdana';
  background-color: white;
}

.editor-footer {
  flex-shrink: 0;
  height: 36px; /* FIXED HEIGHT */
  display: flex;
  justify-content: space-between;
  padding: 4px 8px;
}
</style>
